jdbc:
  driverClassName: com.mysql.jdbc.Driver
  jdbc.url: jdbc:mysql://127.0.0.1:3306/test01
  jdbc.username: root
  jdbc.password: 12345678

  #激活配置文件 需要指定其它的配置文件名称
spring:
  profiles:
    active: abc,def
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test01
    username: root
    password: 12345678
#修改端口
server:
  port: 80

logging:
  level:
    com.example: debug
    org.springframework: info
mybatis:
  # 实体类别名包路径
  type-aliases-package: com.example.pojo
  # 映射文件路径
  # mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

redis:
  host: localhost
  port: 6379




